#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t cm"

$L "Welcome to Android `getprop ro.build.version.release` / `getprop ro.modversion`";

$L " __  __ _       _    _____ __  __      _           "
$L " ";
